# Generated by Django 5.0.1 on 2024-01-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_appointment_appoint_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='slot',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
