# Generated by Django 5.0.1 on 2024-01-25 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_timeslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appoint_date',
        ),
    ]
