# Generated by Django 5.0.1 on 2024-01-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_appointment_appoint_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='slots',
            field=models.CharField(max_length=10),
        ),
    ]
