# Generated by Django 5.0.1 on 2024-01-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_timeslot_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='slots',
            field=models.CharField(max_length=20),
        ),
    ]
