# Generated by Django 5.0.1 on 2024-01-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_appointment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appoint_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
